version: '3.4'

services:
    sut:
        build:
            context: ..
            dockerfile: docker/Dockerfile
            target: builder
        working_dir: /usr/local/go/src/github.com/lynxis/debos/actions
        command: go test
